"""Added account_balance column to user table to track how much they're up or down betting on college football games

Revision ID: aa358750a467
Revises: da7dc054dbe6
Create Date: 2023-08-07 13:01:34.101100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa358750a467'
down_revision = 'da7dc054dbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('account_balance')

    # ### end Alembic commands ###
